#!/bin/sh
# set -x

. /lib/functions.sh

CONFIG=koolproxy
KP_DIR=/usr/share/koolproxy
TMP_DIR=/tmp/koolproxy
LOGFILE="/var/log/koolproxy.log"

KP_DAT=false
DAILY_TXT=false
KOOLPROXY_TXT=false
YHOSTS_TXT=false
STEVEN_TXT=false
ADG_TXT=false
ANTIAD_TXT=false
ADGK_TXT=false
KOOLPROXY_IPSET_CONF=false
DNSMASQ_ADBLOCK=false
USER_TXT=false

alias WGET='wget --no-check-certificate -4 -c -T 8 -t 10'

config_t_get() {
	local index=0
	[ -n "$4" ] && index=$4
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}

limit_log() {
	local log=$1
	[ ! -f "$log" ] && return
	local sc=100
	[ -n "$2" ] && sc=$2
	local count=$(grep -c "" $log)
	if [ $count -gt $sc ];then
		let count=count-$sc
		sed -i "1,$count d" $log
	fi
}

init_env() {
	rm -rf "$TMP_DIR"
	mkdir -p "$TMP_DIR"
}

restart_koolproxy() {
	/etc/init.d/koolproxy restart
}

__compare_file() {
	local descript=$1
	local localPath=$2
	local remoteUrl=$3

	echo $(date "+%F %T"): ------------------- $descript更新 ------------------- >>$LOGFILE
	local filename=`basename $localPath`
	local remotePath="$TMP_DIR/$filename"
	WGET "$remoteUrl" -q -O "$remotePath"
	if [ "$?" == "0" ]; then
		if [ -f "$localPath" ]; then
			localMD5=`md5sum "$localPath" | awk '{print $1}'`
			localNum=`cat "$localPath" | grep -v '^!' | wc -l`
		else
			localMD5="文件不存在"
			localNum="0"
		fi
		remoteMD5=`md5sum "$remotePath" | awk '{print $1}'`
		remoteNum=`cat "$remotePath" | grep -v '^!' | wc -l`

		echo $(date "+%F %T"): 本地版本MD5：$localMD5 >>$LOGFILE
		echo $(date "+%F %T"): 本地版本条数：$localNum >>$LOGFILE
		echo >>$LOGFILE
		echo $(date "+%F %T"): 在线版本MD5：$remoteMD5 >>$LOGFILE
		echo $(date "+%F %T"): 在线版本条数：$remoteNum >>$LOGFILE
		echo >>$LOGFILE

		if [ "$localMD5" != "$remoteMD5" ];then
			echo $(date "+%F %T"): 检测到更新，开始更新规则！ >>$LOGFILE
			mv -f "$remotePath" "$localPath"
			echo $(date "+%F %T"): 更新成功！ >>$LOGFILE
			echo >>$LOGFILE
			return 0
		fi
	else
		echo "$(date "+%F %T"): 获取在线版本时出现错误! " >>$LOGFILE
		echo >>$LOGFILE
	fi
	return 1
}

__update_rule() {
	local name
	local file
	local exrule
	local enable
	config_get name $1 name
	config_get file $1 file
	config_get exrule $1 url
	config_get enable $1 load
	if [ -n "$file" ] && [ -n "$exrule" ]; then
		if [ $enable -ne 1 ]; then
			return
		fi
		__compare_file "$name" "$KP_DIR/data/rules/$file" "$exrule"
		if [ "$?" == "0" ]; then
			uci set koolproxy.$1.time="`date +%Y-%m-%d" "%H:%M`"
			uci commit koolproxy
			RESTART_KOOLPROXY=true
		fi
		cat $KP_DIR/data/rules/$file >>$KP_DIR/data/rules/user.txt
		echo >>$LOGFILE
	fi
}

update_rss_rules() {
	if [ $USER_TXT = true ]; then
		cp $KP_DIR/data/user.txt $KP_DIR/data/rules/user.txt
		config_foreach __update_rule rss_rule
	#else
		#rm -rf $KP_DIR/data/rules/user.txt
	fi
}


	
update_rules() {
	echo $(date "+%F %T"): ------------------- 内置规则更新 ------------------- >>$LOGFILE
	if [ $KP_DAT = true ]; then
		__compare_file "视频规则" "$KP_DIR/data/rules/kp.dat" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/kp.dat"
	#else
		#rm -rf $KP_DIR/data/rules/kp.dat
	fi
	if [ $DAILY_TXT = true ]; then
		__compare_file "每日规则" "$KP_DIR/data/rules/daily.txt" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/daily.txt"
	#else
		#rm -rf $KP_DIR/data/rules/daily.txt
	fi
	if [ $KOOLPROXY_TXT = true ]; then
		__compare_file "静态规则" "$KP_DIR/data/rules/koolproxy.txt" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/koolproxy.txt"
		koolproxy_rules_local=`cat /usr/share/koolproxy/data/rules/koolproxy.txt  | sed -n '3p'|awk '{print $3,$4}'`
		echo $(date "+%F %T"): -------------------静态规则   Version $koolproxy_rules_local >>$LOGFILE
	#else
		#rm -rf $KP_DIR/data/rules/koolproxy.txt
	fi
	if [ $YHOSTS_TXT = true ]; then
		__compare_file "Yhosts规则" "$KP_DIR/data/rules/yhosts.txt" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/yhosts.txt"
		yhosts_rules_local=`cat /usr/share/koolproxy/data/rules/yhosts.txt  | sed -n '1p' | cut -d ":" -f2`
		echo $(date "+%F %T"): -------------------Yhosts规则 Version $yhosts_rules_local >>$LOGFILE
	#else
		#rm -rf $KP_DIR/data/rules/yhosts.txt
	fi
	if [ $STEVEN_TXT = true ]; then
		__compare_file "Steven规则" "$KP_DIR/data/rules/steven.txt" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/steven.txt"
		steven_rules_local=`cat /usr/share/koolproxy/data/rules/steven.txt  | sed -n '2p'|awk '{print $3,$4,$5,$6}'`
		echo $(date "+%F %T"): -------------------Steven规则 Version $steven_rules_local >>$LOGFILE
	#else
		#rm -rf $KP_DIR/data/rules/steven.txt
	fi
	if [ $ADG_TXT = true ]; then
		__compare_file "AdGuard规则" "$KP_DIR/data/rules/adg.txt" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/adg.txt"
		adg_rules_local=`cat /usr/share/koolproxy/data/rules/adg.txt  | sed -n '4p'|awk '{print $4}'`
		echo $(date "+%F %T"): -------------------AdGuard规则 Version $adg_rules_local >>$LOGFILE
	#else
		#rm -rf $KP_DIR/data/rules/adg.txt
	fi
	if [ $ANTIAD_TXT = true ]; then
		__compare_file "AntiAD规则" "$KP_DIR/data/rules/antiad.txt" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/antiad.txt"
		antiad_rules_local=`cat /usr/share/koolproxy/data/rules/antiad.txt  | sed -n '2p' | cut -d "=" -f2`
		echo $(date "+%F %T"): -------------------AntiAD规则 Version $antiad_rules_local >>$LOGFILE
	#else
		#rm -rf $KP_DIR/data/rules/antiad.txt
	fi
	if [ $ADGK_TXT = true ]; then
		__compare_file "Banben规则" "$KP_DIR/data/rules/adgk.txt" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/adgk.txt"
		adgk_rules_local=`cat /usr/share/koolproxy/data/rules/adgk.txt  | sed -n '1p'|awk '{print $3}'`
		echo $(date "+%F %T"): -------------------Banben规则   Version $adgk_rules_local >>$LOGFILE
	#else
		#rm -rf $KP_DIR/data/rules/adgk.txt
	fi
	if [ $KOOLPROXY_IPSET_CONF = true ]; then
		__compare_file "IPSET" "$KP_DIR/koolproxy_ipset.conf" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/koolproxy_ipset.conf"
	#else
		#rm -rf $KP_DIR/koolproxy_ipset.conf
	fi
	if [ $DNSMASQ_ADBLOCK = true ]; then
		__compare_file "Host" "$KP_DIR/dnsmasq.adblock" "https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/dnsmasq.adblock"
	#else
		#rm -rf $KP_DIR/dnsmasq.adblock
	fi
	echo $(date "+%F %T"): ------------------- 内置规则更新成功！ ------------------- >>$LOGFILE
	RESTART_KOOLPROXY=true

}

load_config() {
	config_load $CONFIG

	koolproxy_mode=$(config_t_get global koolproxy_mode 1)
	koolproxy_host=$(config_t_get global koolproxy_host 0)

	if [ "$koolproxy_mode" = "2" ]; then
		# 过滤模式为【IPSET模式】
		KOOLPROXY_IPSET_CONF=true
		if [ "$koolproxy_host" = "1" ];then
			# Adblock Plus Host
			DNSMASQ_ADBLOCK=true
		fi
	fi
	
	local rulelist="$(uci -q get koolproxy.@global[0].koolproxy_rules)"
	for rule in $rulelist
	do
		case "$rule" in
			koolproxy.txt)
				KOOLPROXY_TXT=true
			;;
			daily.txt)
				DAILY_TXT=true
			;;
			kp.dat)
				KP_DAT=true
			;;
			user.txt)
				USER_TXT=true
			;;
		esac
	done

	local rulelist="$(uci -q get koolproxy.@global[0].thirdparty_rules)"
	for rule in $rulelist
	do
		case "$rule" in
			yhosts.txt)
				YHOSTS_TXT=true
			;;
			adg.txt)
				ADG_TXT=true
			;;
			steven.txt)
				STEVEN_TXT=true
			;;
			antiad.txt)
				ANTIAD_TXT=true
			;;
			adgk.txt)
				ADGK_TXT=true
			;;
		esac
	done
	
	if [ "$koolproxy_mode" = "3" ]; then
		# 过滤模式为【视频过滤模式】
		DAILY_TXT=false
		KOOLPROXY_TXT=false
	fi
}

update_adb_host() {
	/usr/sbin/adblockplus >>$LOGFILE 2>&1 &
	if [ "$?" == "0" ]; then
		RESTART_DNSMASQ=true
	fi
}

# main process
init_env
limit_log $LOGFILE

load_config

# update rules
update_rules

# update user rules
update_rss_rules

# update ADB Plus Host
if [ "$koolproxy_mode" == "2" ] && [ "$koolproxy_host" == "1" ];then
	update_adb_host
fi

if [ $RESTART_KOOLPROXY ]; then
	restart_koolproxy
	echo $(date "+%F %T"): 重启koolproxy进程 >>$LOGFILE
fi

init_env
